LENGTH_HEX = 7

LENGTH_TAG_AND_INGREDIENT_CHARFIELD = 200

LENGTH_USER_CHARFIELD = 150

LENGTH_USER_EMAILFIELD = 254

MIN_VALUE_VALIDATOR = 1

MAX_TEXT_RECIPES = 20

MAX_VALUE_VALIDATOR = 32767

MAX_VALUE_VALIDATOR_MINUTES = 4320
