# Generated by Django 3.2.23 on 2024-01-20 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20240120_1209'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IngredientAmount',
            new_name='RecipeIngredient',
        ),
        migrations.RemoveConstraint(
            model_name='recipeingredient',
            name='recipes_ingredientamount_unique_ingredient_in_recipe',
        ),
        migrations.AddConstraint(
            model_name='recipeingredient',
            constraint=models.UniqueConstraint(fields=('recipe', 'ingredient'), name='recipes_recipeingredient_unique_ingredient_in_recipe'),
        ),
    ]
