# Generated by Django 3.2.23 on 2024-01-30 13:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_favorite_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Минимальное количество ингредиентов - 1.'), django.core.validators.MaxValueValidator(10000, message='Максимальное количество ингредиентов - 10000.')], verbose_name='Количество ингредиентов'),
        ),
    ]
