# Generated by Django 3.2.23 on 2024-01-23 12:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0006_auto_20240123_1205'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShippingCart',
            new_name='ShoppingCart',
        ),
        migrations.RemoveConstraint(
            model_name='shoppingcart',
            name='recipes_shippingcart_unique_cart',
        ),
        migrations.AddConstraint(
            model_name='shoppingcart',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='recipes_shoppingcart_unique_cart'),
        ),
    ]
