# Generated by Django 3.2.23 on 2024-01-29 13:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_auto_20240129_1519'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='favorite',
            name='recipes_favorite_unique_favorite',
        ),
        migrations.RemoveConstraint(
            model_name='shoppingcart',
            name='recipes_shoppingcart_unique_cart',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Минимальное время приготовления рецепта в минутах - 1.'), django.core.validators.MaxValueValidator(4320, message='Максимальное время приготовления рецепта в минутах - 4320.')], verbose_name='Время приготовления в минутах'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Минимальное количество ингредиентов - 1.'), django.core.validators.MaxValueValidator(30, message='Максимальное количество ингредиентов - 30.')], verbose_name='Количество ингредиентов'),
        ),
    ]
