# Generated by Django 3.2.23 on 2024-01-29 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_auto_20240129_1629'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ingredient',
            name='recipes_ingredient_unique_name_measurement_unit',
        ),
        migrations.RemoveConstraint(
            model_name='recipeingredient',
            name='recipes_recipeingredient_unique_ingredient_in_recipe',
        ),
        migrations.AddConstraint(
            model_name='ingredient',
            constraint=models.UniqueConstraint(fields=('name', 'measurement_unit'), name='recipes_ingredient_unique_relationship'),
        ),
        migrations.AddConstraint(
            model_name='recipeingredient',
            constraint=models.UniqueConstraint(fields=('recipe', 'ingredient'), name='recipes_recipeingredient_unique_relationship'),
        ),
    ]
